import React, { useState } from "react";
import "./TossForm.css";

const TossForm = ({ teams, onTossResult }) => {
  const [userCall, setUserCall] = useState("");      // heads or tails selected by user
  const [coinResult, setCoinResult] = useState("");  // heads or tails generated by system
  const [winner, setWinner] = useState("");          // team who won the toss
  const [decision, setDecision] = useState("");      // bat/bowl decision

  const handleCoinFlip = () => {
    if (!userCall) return alert("Please choose Heads or Tails");
    const flip = Math.random() < 0.5 ? "heads" : "tails"; // random coin
    setCoinResult(flip);

    // randomly assign which team is caller (e.g., teams[0] calls)
    // If caller guesses right, caller wins; else opponent wins
    const tossWinner =
      flip === userCall.toLowerCase() ? teams[0] : teams[1];

    setWinner(tossWinner);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!winner) return alert("Flip the coin first!");
    onTossResult({ tossWinner: winner, decision });
  };

  return (
    <div className="toss-form-container">
      <h2>Toss</h2>
      <form onSubmit={handleSubmit}>
        {/* User calls Heads or Tails */}
        <select
          value={userCall}
          onChange={(e) => setUserCall(e.target.value)}
          required
        >
          <option value="">Call Heads/Tails</option>
          <option value="heads">Heads</option>
          <option value="tails">Tails</option>
        </select>

        <button type="button" onClick={handleCoinFlip}>
          Flip Coin
        </button>

        {coinResult && (
          <p>
            Coin shows <strong>{coinResult}</strong>.  
            Toss Winner: <strong>{winner}</strong>
          </p>
        )}

        {winner && (
          <select
            value={decision}
            onChange={(e) => setDecision(e.target.value)}
            required
          >
            <option value="">Decision</option>
            <option value="bat">Bat</option>
            <option value="bowl">Bowl</option>
          </select>
        )}

        <button type="submit">Submit Toss</button>
      </form>
    </div>
  );
};

export default TossForm;
